---

apiVersion: v1
kind: Namespace
metadata:
  name: wap-gcb
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: wap-admin-serviceaccount
  namespace: wap-gcb
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wap-admin-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: wap-admin-serviceaccount
    namespace: wap-gcb
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
  namespace: wap-gcb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: wap-admin-serviceaccount
      containers:
      - name: admin
        image: gcr.io/dockyard-ui-demo/whackapod-admin@sha256:6c7a55accc266dd91eec070a976fe620cb2acf2be5396128c97429d2bd6ee5b7
        env:
        - name: APIIMAGE
          value: gcr.io/dockyard-ui-demo/whackapod-api@sha256:52e1c6700f79167f96c4dd37496fef56cc02f8f865ce4d489b3c4d68d22a3124
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: admin
  namespace: wap-gcb
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: game
  labels:
    app: game
  namespace: wap-gcb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: gcr.io/dockyard-ui-demo/whackapod-game@sha256:002c2f211f96155812d7c855040f9a289f6770f04e6537cd8755108e63098469
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: game
  namespace: wap-gcb
spec:
  type: NodePort
  selector:
    app: game
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: wap-gcb
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wap-ingress
  namespace: wap-gcb
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 8080
      - path: /admin/*
        backend:
          serviceName: admin
          servicePort: 8080
      - path: /*
        backend:
          serviceName: game
          servicePort: 8080
